package main

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/yourorg/sso-gateway/internal/apikey"
	"github.com/yourorg/sso-gateway/internal/store"
)

// apiKeyEntry materializes the api_key row we want to persist: it takes
// the plaintext key from the operator and hashes it; the description and
// id come from the store.Config so the same id is visible in the YAML
// audit trail and in the database.
func apiKeyEntry(cfg *store.Config, plaintext, fallbackID string) *apikey.Entry {
	id := fallbackID
	desc := "generated by setup"
	if cfg != nil && len(cfg.API.Keys) > 0 {
		if cfg.API.Keys[0].ID != "" {
			id = cfg.API.Keys[0].ID
		}
		if cfg.API.Keys[0].Description != "" {
			desc = cfg.API.Keys[0].Description
		}
	}
	return &apikey.Entry{
		ID:          id,
		KeyHash:     setupHash(plaintext),
		Description: desc,
	}
}

// insertAPIKey upserts the api key row: if an entry with the same id
// already exists we replace its hash + description so re-running setup
// is safe. The revoked flag is left untouched so an operator who
// revoked a key on purpose is not silently un-revoked.
func insertAPIKey(ctx context.Context, pool *pgxpool.Pool, e *apikey.Entry) error {
	if e == nil {
		return fmt.Errorf("nil api key entry")
	}
	const q = `
INSERT INTO api_keys (id, key_hash, description)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
  key_hash    = EXCLUDED.key_hash,
  description = EXCLUDED.description`
	_, err := pool.Exec(ctx, q, e.ID, e.KeyHash, e.Description)
	if err != nil && err != pgx.ErrNoRows {
		return fmt.Errorf("upsert api key: %w", err)
	}
	return nil
}
